### PR TITLE
Add new HuggingChat model and change System Prompt method

### PR DESCRIPTION
**Pull request by Whitelisted1**
* ~~Added the new model from the HuggingFace UI, `mistralai/Mistral-7B-Instruct-v0.1`~~
* [Added the ability for the module to automatically fetch the available LLMs from the HuggingChat servers](https://github.com/Soulter/hugging-chat-api/pull/105#issuecomment-1749788145)
* Made changes to the method in which the user is able to change the system prompt. Before, the system prompt was set per model and applied to new conversations. With the recent changes, it now applies per conversation. (This change was made because of changes in the HuggingFace API and how they dealt with system prompts)
* [Conversations are now stored as custom Conversation objects instead of just a string with the conversation ID](https://github.com/Soulter/hugging-chat-api/pull/105#issuecomment-1749824995)

Here is how you would set a system prompt with the new changes:
```python
chatbot.new_conversation(switch_to=True, system_prompt="My name is Jane.")

print(chatbot.query("What is my name?")) # Your name is Jane!
```

### CODE REVIEW

**Comment by Whitelisted1** [comment]
Added the `system_prompt` parameter when the ChatBot is being initiated in order to prevent having to create an additional conversation if the user wants to change the system prompt.

**Comment by Whitelisted1** [comment]
With the [most recent commit](https://github.com/Soulter/hugging-chat-api/pull/105/commits/c6a6d9ccbfeeabf0088e16cf1bcd6b934822ba70), we no longer have to manually update the `llms` list everytime HuggingChat makes a change to their available LLMs

**Comment by Whitelisted1** [comment]
Transitioned over to a class based conversation system. Instead of storing all conversations as conversation ids in strings, they are now stored in an object that contains an ID, title, model and system prompt. This is beneficial because it allows us to more easily fetch data relating to conversations.

**Comment by quantumalchemy** [comment]
tried chatbot.switch_llm(3) 
- as shown on the list
for  Mistral-7B
but "IndexError("Out of range of llm index")"

How to switch to this llm?

**Comment by Whitelisted1** [comment]
> tried chatbot.switch_llm(3)
> 
> * as shown on the list
>   for  Mistral-7B
>   but "IndexError("Out of range of llm index")"
> 
> How to switch to this llm?

This pull request has not been merged yet. After it has been merged and a new release is published you will be able to use the `Mistral-7B` model.

**Comment by babycommando** [comment]
this deserve some attention ::]

**Pull request merged**
