### PR TITLE
update: login process changed

### PR DESCRIPTION
**Pull request by ogios**
# Related issues
#45 #46 

# changes include:
- pycharm automatically formats the code😂
- `grantAuth()` process changed

### CODE REVIEW

**Comment by ogios** [comment]
I haven't fully tested it, I only got two accounts, no promise that there are still bugs in it.
it might be more reassuring to test it more times.

**Comment by pakkinlau** [comment]
> I haven't fully tested it, I only got two accounts, no promise that there are still bugs in it. it might be more reassuring to test it more times.

Can you successfully login with your edit? In my computer your version didn't make it work.

**Comment by ogios** [comment]
> Can you successfully login with your edited version? In my computer your version didn't make it work.

Yes it works:
image
And the code is just copied directly from my repo: [Sign.py](https://github.com/ogios/huggingchat-api/blob/e02324fbfe2179bb6796e017a752c30437ee67a2/hugchat_api/core/Sign.py#L90C13-L90C13)
Please provide your error details.

**Comment by Soulter** [comment]
Works so well!!

**Comment by Soulter** [comment]
Published a new version `0.0.8`, use following command to update it.
```bash
pip3 install -upgrade hugchat
```

Thanks to you all!

**Pull request merged**
