### PR TITLE
Fix the error of delete all conversations

### PR DESCRIPTION
**Pull request by kokofixcomputers**
fix delete all conversations with same error

### CODE REVIEW

**Comment by kokofixcomputers** [comment]
YES!!! it finally passed!

**Comment by kokofixcomputers** [comment]
omg

**Comment by kokofixcomputers** [comment]
@Soulter thanks! i fixed another issue with same type

**Review by Soulter — APPROVED** [review]

**Comment by Soulter** [comment]
Thanks!

**Comment by kokofixcomputers** [comment]
No problem!

**Pull request merged**
