### PR TITLE
Added multiple new features and removed unused imports

### PR DESCRIPTION
**Pull request by Whitelisted1**
Added a summarize conversation function and a share conversation function. Currently, the share conversation feature does not work (It links to a blank conversation) as conversation histories don't work.

### CODE REVIEW

**Comment by DeuDeuka** [comment]
man it's will be great if you add model changing system. I can do it on my own, but with every update of your module it will be erased

**Comment by Whitelisted1** [comment]
Yeah, I should be able to do that by tomorrow. I'll create a new pull request when I finish that up, so you can merge this one if you find my changes to be satisfactory.

**Review by Soulter — APPROVED** [review]
LGTM

**Comment by RockChinQ** [comment]
`model` should be `modal`, I'll fix it lol.

**Comment by Whitelisted1** [comment]
Sorry guess I missed that

**Comment by RockChinQ** [comment]
> Sorry guess I missed that

never mind, already fixed.

**Comment by DeuDeuka** [comment]
> Yeah, I should be able to do that by tomorrow. I'll create a new pull request when I finish that up, so you can merge this one if you find my changes to be satisfactory.
I found that all models are placed in file https://huggingface.co/chat/conversation/6455bb23bdad19acb30c20b2 in 'const data = ' in one line. Could be useful

**Comment by RockChinQ** [comment]
> > Yeah, I should be able to do that by tomorrow. I'll create a new pull request when I finish that up, so you can merge this one if you find my changes to be satisfactory.
> 
> I found that all models are placed in file https://huggingface.co/chat/conversation/6455bb23bdad19acb30c20b2 in 'const data = ' in one line. Could be useful

file a issue for this feature plz

**Pull request merged**
