### PR TITLE
Add functions to login in into huggingface and grant auth to huggingchat

### PR DESCRIPTION
**Pull request by ogios**
add a class called `Login()` with a little bit modification. 
it requires two params, `email` and `passwd`, login using the function `main()`.
it returns a RequestsCookieJar.
changed the function `cli()` a little bit, now it can log in and save cookies.
also changed some descriptions in the README file. 
you can test if it works, I've tested a few times, fine til now.

### CODE REVIEW

**Comment by RockChinQ** [comment]
感谢贡献！  
比较建议将鉴权有关的配置项（账密、cookies）都统一到一个地方，如ChatBot的构造函数。一是因为HF已开源前端代码，之后使用账密等官方鉴权流程的稳定性很有保障。二是考虑到代码整洁和调用方便，鉴权有关的配置项统一起来会更好。  
可以参考一下[acheong08/ChatGPT](https://github.com/acheong08/ChatGPT)的实现风格。
当然，Login独立一个类也是一种很好的设计，建议再考虑一下具体的实现方式。

**Comment by ogios** [comment]
抱歉这是我第一次pull request，不是很熟悉，还有这么多commit只为了修改README文件。
这次修改了很多内容
- cli() 移到了`cli.py`里，为登录加入了大部分内容，并且加入了命令行参数方便使用
- 为 Login() 单独开了一个`login.py`，并且加入了 `saveCookies()` 和 `loadCookies()` 来保存和加载cookies，登录方法重命名为 `login()`
- cookies默认存放位置为 `usercookies/.json`

Sorry this is my first pull request, not familiar with it, and there are so many commit just to modify the README file.
A lot of things have been revised this time
- cli ()  is moved to 'cli.py', modified a lot for the login function,  and added command-line arguments
- Makes a separate 'login.py' for Login(), and adds' saveCookies() 'and' loadCookies() 'to save and load them. The login method is renamed to' login() '
- The default location for storing cookies is usercookies/.json

**Comment by Soulter** [comment]
> 抱歉这是我第一次pull request，不是很熟悉，还有这么多commit只为了修改README文件。 这次修改了很多内容
> 
> * cli() 移到了`cli.py`里，为登录加入了大部分内容，并且加入了命令行参数方便使用
> * 为 Login() 单独开了一个`login.py`，并且加入了 `saveCookies()` 和 `loadCookies()` 来保存和加载cookies，登录方法重命名为 `login()`
> * cookies默认存放位置为 `usercookies/<email>.json`
> 
> Sorry this is my first pull request, not quiet familiar with it. And there are so many commit just to modify the README file😂. A lot of things have been revised this time
> 
> * cli ()  has been moved to 'cli.py', modified a lot for the login function,  and added command-line arguments.
> * Created a new file called 'login.py', added ' saveCookies() 'and' loadCookies() 'to save and load them. The login method is renamed to 'login()'
> * The default location for storing cookies is usercookies/.json

感谢提交PR，很棒的功能！没关系~

Cool features! Thanks for your contributions!

**Review by Soulter — APPROVED** [review]
LGTM

**Pull request merged**
