### PR TITLE
feat(cli): add new arg -c ,continued conv,change list -> tuple

### PR DESCRIPTION
**Pull request by akhil3417**
"Add support for continuing a previous conversation in the HuggingChat CLI. The -c option can now be used when running the CLI to automatically switch to the most recent conversation and resume chatting."

### CODE REVIEW

**Comment by Soulter** [comment]
Hello, the latest commit has fixed a unit test problem, please merge it and push again to pass the unit test.

**Comment by akhil3417** [comment]
failed tests are due to rate limits

**Comment by akhil3417** [comment]
their might be a bug ,let me try to resolve

**Comment by akhil3417** [comment]
everything's ok. its was fixed.

**Pull request merged**
